[package]
name = "smoltar"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
flate2 = "1.0.30"
tar = "0.4.41"

[profile.release]
strip = "debuginfo"
codegen-units = 1
panic = "abort"
lto = true
